osx_image: xcode10.1
language: swift
script:
  - xcodebuild 
  - workspace ChooseBiggerOne.xcworkspace 
  - scheme ChooseBiggerOne 
  - sdk iphonesimulator 
  ONLY_ACTIVE_ARCH=NO 
  clean 
  build 
  test 
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'ChooseBiggerOne'
