osx_image: xcode10.1
language: swift
script:
  - xcodebuild -workspace ChooseBiggerOne.xcworkspace -scheme ChooseBiggerOne -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0' ONLY_ACTIVE_ARCH=NO clean build test | xcpretty 
  - xcodebuild -workspace ChooseBiggerOne.xcworkspace -scheme RefactoringDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0' ONLY_ACTIVE_ARCH=NO clean build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'ChooseBiggerOne' -t 98cd8a93-149c-4475-b888-605dc819a37b
  - bash <(curl -s https://codecov.io/bash) -J 'RefactoryingDemo' -t 98cd8a93-149c-4475-b888-605dc819a37b
