language: swift
script:
  - xcodebuild -project ChooseBiggerOne.xcodeproj -scheme ChooseBiggerOne -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
