osx_image: xcode10.1
language: swift
script:
  - xcodebuild -project ChooseBiggerOne.xcodeproj -scheme ChooseBiggerOne -sdk iphoneos ONLY_ACTIVE_ARCH=NO clean build test CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
